2023-01-17 08:54:03.551 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly
2023-01-17 08:54:12.299 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.0.143 (192.168.0.143). Requested URL: '/auth/token'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0)
2023-01-17 08:54:12.489 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.0.143 (192.168.0.143). Requested URL: '/api/websocket'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0)
2023-01-17 08:54:20.481 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Canon TS3100 series' for ipp integration not ready yet: Invalid response from API: Error occurred while communicating with IPP server.; Retrying in background
2023-01-17 08:54:29.479 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.0.143 (192.168.0.143). Requested URL: '/auth/login_flow/e20672efe1d3cdaff19f9ad8599381d3'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0)
2023-01-17 08:54:33.472 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.0.143 (192.168.0.143). Requested URL: '/auth/login_flow/e20672efe1d3cdaff19f9ad8599381d3'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0)
2023-01-17 08:54:40.223 WARNING (Thread-4) [matplotlib.font_manager] Matplotlib is building the font cache; this may take a moment.
2023-01-17 08:54:42.768 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.0.143 (192.168.0.143). Requested URL: '/auth/login_flow/e20672efe1d3cdaff19f9ad8599381d3'. (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0)
2023-01-17 09:02:12.935 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 109-95-97-142.gorcom.ru (109.95.97.142). Requested URL: '/auth/token'. (Home Assistant/2022.12.0-3026 (Android 11; Redmi Note 9 Pro))
2023-01-17 09:02:13.220 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 109-95-97-142.gorcom.ru (109.95.97.142). Requested URL: '/api/websocket'. (Mozilla/5.0 (Linux; Android 11; Redmi Note 9 Pro Build/RKQ1.200826.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36 Home Assistant/2022.12.0-3026 (Android 11; Redmi Note 9 Pro))
2023-01-17 09:02:34.010 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.0.193 (192.168.0.193). Requested URL: '/auth/login_flow/cb569af057f11b2a762f6e50c23c75a5'. (Mozilla/5.0 (Linux; Android 11; Redmi Note 9 Pro Build/RKQ1.200826.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36 Home Assistant/2022.12.0-3026 (Android 11; Redmi Note 9 Pro))
2023-01-17 09:05:55.363 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.0.158 (192.168.0.158). Requested URL: '/auth/token'. (Home Assistant/2022.12.0-3026 (Android 10; MI 8))
2023-01-17 09:05:55.575 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.0.158 (192.168.0.158). Requested URL: '/api/websocket'. (Mozilla/5.0 (Linux; Android 10; MI 8 Build/QKQ1.190828.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36 Home Assistant/2022.12.0-3026 (Android 10; MI 8))
2023-01-17 13:37:11.946 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
2023-01-17 14:50:51.382 WARNING (Thread-5) [pychromecast.socket_client] [Телевизор в гостиной(192.168.0.176):8009] Heartbeat timeout, resetting connection
2023-01-17 14:51:21.641 ERROR (Thread-5) [pychromecast.socket_client] [Телевизор в гостиной(192.168.0.176):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.0.176', 8009)), retrying in 5.0s
2023-01-17 16:54:01.472 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
